Repository dpkp/kafka-python, pull requests merged in 2023-08, with the labels that each got.

#2334 Update usage.rst
  docs/usage.rst
Labels: documentation

#2319 docs: Fix a few typos
  kafka/codec.py
  kafka/coordinator/base.py
  kafka/record/abc.py
  kafka/record/legacy_records.py
Labels: documentation

#2308 Update usage.rst
  docs/usage.rst
Labels: documentation

#2329 Use isinstance in builtin crc32
  kafka/record/_crc32c.py
Labels: enhancement

#2387 Update setup.py to install zstandard instead of python-zstandard
  setup.py
Labels: packaging
